[package]
name = "solana-readonly-account"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = ">=0", default-features = false, features = ["as_ref", "as_mut", "deref", "from", "into", "as_mut", "deref_mut"] }
solana-program ="^1"
solana-sdk = { version = "^1", optional = true }

[dev-dependencies]
spl-token-2022 = "^0.7"
