[package]
name = "solana-readonly-account"
version = "1.0.0"
edition = "2021"

[dependencies]
derive_more = { version = "^0.99", default-features = false, features = ["deref", "deref_mut", "as_ref", "as_mut", "from", "into"] }
solana-program ="^1"
solana-sdk = { version = "^1", optional = true }

[dev-dependencies]
spl-token-2022 = "^0.7"
